# app.py — Streamlit demo for the Educator Copilot.
# Runs in EXTRACT_MODE=demo with no API key and no live systems: every tool call
# flows through the MCP gateway against deterministic fixtures.
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import streamlit as st

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_HERE.parent / "platform_core"))
sys.path.insert(0, str(_HERE.parent))

os.environ.setdefault("EXTRACT_MODE", "demo")
os.environ.setdefault("CONNECTOR_MODE", "fixture")

from agent.graph import build_graph, get_graph_visualization

st.set_page_config(page_title="Educator Copilot", page_icon="🧑‍🏫", layout="wide")
st.title("🧑‍🏫 Educator Copilot")
st.caption("Bounded, governed demo — drafts lessons, rubrics, quizzes, and announcements grounded in approved "
           "curriculum and places DRAFTS in the LMS; never auto-publishes. Demo mode: no API key, deterministic "
           "fixtures, every tool call audited at the gateway.")

samples = json.loads((_HERE / "data" / "fixtures" / "sample_requests.json").read_text())

with st.sidebar:
    st.header("Request")
    idx = st.selectbox("Sample request", range(len(samples)),
                       format_func=lambda i: samples[i]["request_id"])
    sample = samples[idx]
    artifact_type = st.selectbox(
        "Artifact type", ["lesson", "rubric", "quiz", "announcement", "differentiation"],
        index=["lesson", "rubric", "quiz", "announcement", "differentiation"].index(
            sample.get("artifact_type", "lesson")),
    )
    st.markdown("**Mermaid workflow**")
    st.code(get_graph_visualization(), language="mermaid")

instructions = st.text_area("Instructions", sample.get("instructions", ""), height=90)

if st.button("Run copilot", type="primary"):
    seed = dict(sample)
    seed["instructions"] = instructions
    seed["artifact_type"] = artifact_type
    graph = build_graph(use_memory=False)
    out = graph.invoke(seed)

    st.subheader("Draft artifact")
    st.write(out.get("draft_artifact", ""))
    st.caption(f"Generated by: {out.get('generated_by')} · disposition: {out.get('recommended_action')} "
               f"· status: {out.get('case_status')} · draft_id: {out.get('draft_id')} "
               f"· published: {out.get('published')}")

    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Grounding report")
        st.json(out.get("grounding_report", {}))
        st.subheader("Compliance findings")
        st.write(out.get("compliance_findings") or "None")
    with col2:
        st.subheader("Audit trail (gateway + workflow)")
        st.json(out.get("audit_trail", []))

st.divider()
st.caption("Decision-support accelerator. Not a system of record. Every artifact is a DRAFT; publishing and "
           "due-date changes require a verified educator approval bound at the gateway.")
