# app.py — Streamlit demo for Operations & Service Desk.
# Runs in EXTRACT_MODE=demo with no API key and no live systems: every tool call
# flows through the MCP gateway against deterministic fixtures.
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import streamlit as st

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_HERE.parent / "platform_core"))
sys.path.insert(0, str(_HERE.parent))

os.environ.setdefault("EXTRACT_MODE", "demo")
os.environ.setdefault("CONNECTOR_MODE", "fixture")

from agent.graph import build_graph, get_graph_visualization

st.set_page_config(page_title="Operations & Service Desk", page_icon="🛠️", layout="wide")
st.title("🛠️ Operations & Service Desk")
st.caption("Bounded, governed demo — diagnoses issues, answers policy, files low-risk tickets, and drafts documents; "
           "privileged remediation and financial approvals need human approval. Security/identity/safeguarding concerns escalate. "
           "Demo mode: no API key, deterministic fixtures, every tool call audited at the gateway.")

samples = json.loads((_HERE / "data" / "fixtures" / "sample_requests.json").read_text())

with st.sidebar:
    st.header("Service request")
    idx = st.selectbox("Sample request", range(len(samples)),
                       format_func=lambda i: samples[i]["request_id"])
    sample = samples[idx]
    track = st.selectbox("Track", ["it", "admin"],
                         index=["it", "admin"].index(sample.get("track", "it")))
    st.markdown("**Mermaid workflow**")
    st.code(get_graph_visualization(), language="mermaid")

request = st.text_area("Request", sample.get("request", ""), height=90)

if st.button("Run service desk", type="primary"):
    seed = dict(sample)
    seed["request"] = request
    seed["track"] = track
    graph = build_graph(use_memory=False)
    out = graph.invoke(seed)

    st.subheader("Resolution")
    st.write(out.get("draft_resolution", ""))
    st.caption(f"Generated by: {out.get('generated_by')} · disposition: {out.get('recommended_action')} "
               f"· status: {out.get('case_status')}")

    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Policy / diagnostic")
        st.json({"kb_hits": out.get("kb_hits", []), "diagnostic": out.get("diagnostic", {})})
        st.subheader("Grounding report")
        st.json(out.get("grounding_report", {}))
        st.subheader("Compliance findings")
        st.write(out.get("compliance_findings") or "None")
    with col2:
        st.subheader("Audit trail (gateway + workflow)")
        st.json(out.get("audit_trail", []))

st.divider()
st.caption("Decision-support accelerator. Not a system of record. AI diagnoses and drafts; privileged remediation "
           "and financial approvals execute only with a verified human approval.")
