# app.py — Streamlit demo for Document & Accessibility Services.
# Runs in EXTRACT_MODE=demo with no API key and no live systems: every tool call
# flows through the MCP gateway against deterministic fixtures.
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import streamlit as st

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_HERE.parent / "platform_core"))
sys.path.insert(0, str(_HERE.parent))

os.environ.setdefault("EXTRACT_MODE", "demo")
os.environ.setdefault("CONNECTOR_MODE", "fixture")

from agent.graph import build_graph, get_graph_visualization

st.set_page_config(page_title="Document & Accessibility Services", page_icon="📄", layout="wide")
st.title("📄 Document & Accessibility Services")
st.caption("Bounded, governed demo — classifies, extracts, validates, and prepares enrollment updates; "
           "transforms approved content into accessible/translated drafts. The enrollment write needs human approval. "
           "Demo mode: no API key, deterministic fixtures, every tool call audited at the gateway.")

samples = json.loads((_HERE / "data" / "fixtures" / "sample_requests.json").read_text())

with st.sidebar:
    st.header("Document request")
    idx = st.selectbox("Sample request", range(len(samples)),
                       format_func=lambda i: samples[i]["request_id"])
    sample = samples[idx]
    mode = st.selectbox("Mode", ["enrollment", "accessibility"],
                        index=["enrollment", "accessibility"].index(sample.get("mode", "enrollment")))
    st.markdown("**Mermaid workflow**")
    st.code(get_graph_visualization(), language="mermaid")

question = st.text_area("Request", sample.get("question", ""), height=90)

if st.button("Run pipeline", type="primary"):
    seed = dict(sample)
    seed["question"] = question
    seed["mode"] = mode
    graph = build_graph(use_memory=False)
    out = graph.invoke(seed)

    st.subheader("Draft / summary")
    st.write(out.get("draft_message", ""))
    st.caption(f"Generated by: {out.get('generated_by')} · disposition: {out.get('recommended_action')} "
               f"· status: {out.get('case_status')}")

    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Extracted / completeness / artifacts")
        st.json({"doc_type": out.get("doc_type", ""),
                 "extracted_fields": out.get("extracted_fields", {}),
                 "low_confidence_fields": out.get("low_confidence_fields", []),
                 "completeness": out.get("completeness", {}),
                 "accessible_artifacts": out.get("accessible_artifacts", {})})
        st.subheader("Grounding report")
        st.json(out.get("grounding_report", {}))
        st.subheader("Compliance findings")
        st.write(out.get("compliance_findings") or "None")
    with col2:
        st.subheader("Audit trail (gateway + workflow)")
        st.json(out.get("audit_trail", []))

st.divider()
st.caption("Decision-support accelerator. Not a system of record. AI never decides admissions or eligibility; "
           "the enrollment-record write executes only with a verified human approval.")
