# app.py — Streamlit demo for the Student Success & Engagement agent.
# Runs in EXTRACT_MODE=demo with no API key and no live systems: every tool call
# flows through the MCP gateway against deterministic fixtures.
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import streamlit as st

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_HERE.parent / "platform_core"))
sys.path.insert(0, str(_HERE.parent))

os.environ.setdefault("EXTRACT_MODE", "demo")
os.environ.setdefault("CONNECTOR_MODE", "fixture")

from agent.graph import build_graph, get_graph_visualization

st.set_page_config(page_title="Student Success & Engagement", page_icon="🧭", layout="wide")
st.title("🧭 Student Success & Engagement")
st.caption("Bounded, governed demo — assembles authorized signals into an intervention plan; the counselor owns outreach. "
           "Demo mode: no API key, deterministic fixtures, every tool call audited at the gateway.")

samples = json.loads((_HERE / "data" / "fixtures" / "sample_requests.json").read_text())

with st.sidebar:
    st.header("Case")
    idx = st.selectbox("Sample case", range(len(samples)),
                       format_func=lambda i: samples[i]["request_id"])
    sample = samples[idx]
    trigger_event = st.selectbox("Trigger event",
                                 ["absences", "missing_work", "disengagement", "deadline"],
                                 index=["absences", "missing_work", "disengagement", "deadline"].index(
                                     sample.get("trigger_event", "disengagement")))
    st.markdown("**Mermaid workflow**")
    st.code(get_graph_visualization(), language="mermaid")

student_ref = st.text_input("Student reference", sample.get("student_ref", ""))

if st.button("Run student-success workflow", type="primary"):
    seed = dict(sample)
    seed["trigger_event"] = trigger_event
    seed["student_ref"] = student_ref
    graph = build_graph(use_memory=False)
    out = graph.invoke(seed)

    st.subheader("Intervention plan + draft outreach")
    st.write(out.get("draft_plan", ""))
    st.caption(f"Generated by: {out.get('generated_by')} · disposition: {out.get('recommended_action')} "
               f"· status: {out.get('case_status')}")

    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Assembled evidence")
        st.json(out.get("evidence", {}))
        st.subheader("Grounding report")
        st.json(out.get("grounding_report", {}))
        st.subheader("Fairness report")
        st.json(out.get("fairness_report", {}))
        st.subheader("Compliance findings (PPRA)")
        st.write(out.get("compliance_findings") or "None")
    with col2:
        st.subheader("Audit trail (gateway + workflow)")
        st.json(out.get("audit_trail", []))

st.divider()
st.caption("Decision-support accelerator. Not a system of record. Prediction, explanation, and the human "
           "decision are kept separate; the agent never sends outreach autonomously.")
