# app.py — Streamlit demo for the Student & Family Services Concierge.
# Runs in EXTRACT_MODE=demo with no API key and no live systems: every tool call
# flows through the MCP gateway against deterministic fixtures.
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import streamlit as st

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_HERE.parent / "platform_core"))
sys.path.insert(0, str(_HERE.parent))

os.environ.setdefault("EXTRACT_MODE", "demo")
os.environ.setdefault("CONNECTOR_MODE", "fixture")

from agent.graph import build_graph, get_graph_visualization

st.set_page_config(page_title="Student & Family Concierge", page_icon="🎓", layout="wide")
st.title("🎓 Student & Family Services Concierge")
st.caption("Bounded, governed demo — answers grounded in approved content; staff own consequential actions. "
           "Demo mode: no API key, deterministic fixtures, every tool call audited at the gateway.")

samples = json.loads((_HERE / "data" / "fixtures" / "sample_requests.json").read_text())

with st.sidebar:
    st.header("Request")
    idx = st.selectbox("Sample request", range(len(samples)),
                       format_func=lambda i: samples[i]["request_id"])
    sample = samples[idx]
    authenticated = st.checkbox("Authenticated", value=sample.get("authenticated", False))
    st.markdown("**Mermaid workflow**")
    st.code(get_graph_visualization(), language="mermaid")

question = st.text_area("Question", sample["question"], height=90)

if st.button("Run concierge", type="primary"):
    seed = dict(sample)
    seed["question"] = question
    seed["authenticated"] = authenticated
    graph = build_graph(use_memory=False)
    out = graph.invoke(seed)

    st.subheader("Response")
    st.write(out.get("draft_response", ""))
    st.caption(f"Generated by: {out.get('generated_by')} · disposition: {out.get('recommended_action')} "
               f"· status: {out.get('case_status')}")

    col1, col2 = st.columns(2)
    with col1:
        st.subheader("Grounding report")
        st.json(out.get("grounding_report", {}))
        st.subheader("Compliance findings")
        st.write(out.get("compliance_findings") or "None")
    with col2:
        st.subheader("Audit trail (gateway + workflow)")
        st.json(out.get("audit_trail", []))

st.divider()
st.caption("Decision-support accelerator. Not a system of record. AI never decides admissions, "
           "financial aid, discipline, eligibility, or placement.")
